services:
  gitlab:
    image: gitlab/gitlab-ee:18.0.0-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.homelab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.homelab.local:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '10.0.0.104:8929:8929'
      - '10.0.0.104:443:443'
      - '10.0.0.104:2424:22'
    volumes:
      - '/home/ansible/gitlab/config:/etc/gitlab'
      - '/home/ansible/gitlab/logs:/var/log/gitlab'
      - '/home/ansible/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
