FROM jenkins/jenkins@sha256:057fc64d47b4e20514768ee2264d200ba5c5a206f89b1f459a4dbe32b0692dbd
USER root
RUN apt-get update && apt-get install -y ansible git build-essential rsync curl \
  jq yq
USER jenkins
RUN jenkins-plugin-cli --plugins \
  "ansible configuration-as-code git ldap "
