- name: provision jenkins on docker
  hosts: miniserver
  become: true
  vars:
    images:
      - docker:dind
      - jenkins/jenkins:2.504.1-jdk21
  tasks:
    - name: copy all dockerfiles to remote machine(s)
      ansible.builtin.copy:
        src: ../dockerfiles
        dest: /tmp/

    - name: create "jenkins" network per documentation
      community.docker.docker_network:
        name: jenkins

    - name: pull docker:dind image prior to running it
      community.docker.docker_image_pull:
        name: "{{ item  }}"
      loop: "{{ images }}"

    - name: run jenkins container with specific settings
      community.docker.docker_container:
        name: jenkins-docker
        detach: true
        auto_remove: true
        privileged: true
        networks:
          - name: jenkins
            aliases:
              - docker
        env:
          DOCKER_TLS_CERTDIR=/certs
        volumes:
          - jenkins-docker-certs:/certs/client
          - jenkins-data:/var/jenkins_home
        published_ports:
          - 2376:2376
        image: docker:dind
        #volume_driver: overlay2 default on linux

    - name: build jenkins images in dockerfiles remote_src at /tmp/dockerfiles
      ansible.builtin.shell:
        cmd: docker build -t myjenkins-blueocean:2.504.1-1 -f Dockerfile_jenkins .
        chdir: /tmp/dockerfiles

    - name: run jenkins container with specific settings
      community.docker.docker_container:
        name: jenkins-blueocean
        restart: true
        restart_policy: on-failure
        detach: true
        networks:
          - name: jenkins
        env:
          DOCKER_CERT_PATH=/certs/client
          DOCKER_TLS_VERIFY=1
        volumes:
          - jenkins-docker-certs:/certs/client:ro
          - jenkins-data:/var/jenkins_home
        published_ports:
          - 8080:8080
          - 50000:50000
        image: myjenkins-blueocean:2.504.1-1
        #volume_driver: overlay2 default on linux



